server:
  http_listen_port: 9081
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:

- job_name: artiq_log
  pipeline_stages:
  static_configs:
    - targets:
        - localhost
      labels:
        job: artiqlog
        host: mongkok
        __path__: 'C:\\Users\\EGGS1\\Documents\\.labrad\\logfiles\\artiq\\*'

  # Additional labels to assign to the logs
#  [ <labelname>: <labelvalue> ... ]